---
version: '3.3'

services:
  backend:
    container_name: varys-backend
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      caddy:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: unless-stopped
    volumes:
      - ./backend:/app

  caddy:
    environment:
      DOMAIN: ${DOMAIN}
      PGADMIN_DOMAIN: ${PGADMIN_DOMAIN}
    image: caddy:2.6.2-alpine
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
      - '9000:9000'
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pg_admin:
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4:6.15
    ports:
      - '4000:80'
    restart: unless-stopped

volumes:
  caddy_config: null
  caddy_data: null
