"""init

Revision ID: 06f1164c244b
Revises: 
Create Date: 2023-03-04 18:39:45.881949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06f1164c244b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "train_station",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("interchange", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("row_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("id", "name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "connecting_station",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connecting_id", sa.String(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connecting_id"],
            ["train_station.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["train_station.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connecting_station")
    op.drop_table("train_station")
    # ### end Alembic commands ###
