"""add-transit-time

Revision ID: 17eb7834d42b
Revises: 06f1164c244b
Create Date: 2023-03-05 07:19:08.778018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17eb7834d42b"
down_revision = "06f1164c244b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connecting_station", sa.Column("transit_time", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connecting_station", "transit_time")
    # ### end Alembic commands ###
