"""update_conn_unique

Revision ID: 58b858017754
Revises: 17eb7834d42b
Create Date: 2023-03-06 04:27:00.515881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58b858017754"
down_revision = "17eb7834d42b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "connecting_station", ["id", "connecting_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "connecting_station", type_="unique")
    # ### end Alembic commands ###
