"""update-connecting-station

Revision ID: 76d9073b3366
Revises: 58b858017754
Create Date: 2023-03-12 11:05:16.714520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76d9073b3366"
down_revision = "58b858017754"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connecting_station", sa.Column("waiting_time", sa.Integer(), nullable=True)
    )
    op.add_column("connecting_station", sa.Column("line", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connecting_station", "line")
    op.drop_column("connecting_station", "waiting_time")
    # ### end Alembic commands ###
